/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "inverse-primary": "#94a3b8",
        "secondary-container": "#d0e1fb",
        "secondary": "#505f76",
        "surface-tint": "#334155",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-container": "#ffd2be",
        "tertiary": "#7e3000",
        "surface-variant": "#e4e1ee",
        "surface": "#fcf8ff",
        "surface-bright": "#fcf8ff",
        "on-surface": "#1b1b24",
        "on-surface-variant": "#464555",
        "secondary-fixed": "#d3e4fe",
        "inverse-surface": "#302f39",
        "outline-variant": "#c7c4d8",
        "primary-container": "#334155",
        "tertiary-container": "#a44100",
        "primary": "#334155",
        "on-primary-fixed": "#0f172a",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dcd8e5",
        "on-secondary-container": "#54647a",
        "primary-fixed": "#e2e8f0",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f5f2ff",
        "secondary-fixed-dim": "#b7c8e1",
        "error-container": "#ffdad6",
        "surface-container-high": "#eae6f4",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f0ecf9",
        "on-tertiary-fixed-variant": "#7b2f00",
        "tertiary-fixed-dim": "#ffb695",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f3effc",
        "tertiary-fixed": "#ffdbcc",
        "primary-fixed-dim": "#cbd5e1",
        "on-primary-container": "#f1f5f9",
        "error": "#ba1a1a",
        "on-background": "#1b1b24",
        "surface-container-highest": "#e4e1ee",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#1e293b",
        "background": "#fcf8ff",
        "outline": "#777587",
        "on-tertiary-fixed": "#351000",
        "status-available": "#dcfce7",
        "on-status-available": "#166534",
        "status-occupied": "#fee2e2",
        "on-status-occupied": "#991b1b",
        "status-away": "#fef9c3",
        "on-status-away": "#854d0e"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "xl": "48px",
          "md": "16px",
          "gutter": "16px",
          "lg": "24px",
          "container-max": "1280px",
          "base": "4px",
          "sm": "8px",
          "xs": "4px"
      },
      "fontFamily": {
          "display-lg-mobile": ["Inter", "sans-serif"],
          "mono-timer": ["Inter", "sans-serif"],
          "body-sm": ["Inter", "sans-serif"],
          "headline-md": ["Inter", "sans-serif"],
          "label-bold": ["Inter", "sans-serif"],
          "body-base": ["Inter", "sans-serif"],
          "display-lg": ["Inter", "sans-serif"]
      },
      "fontSize": {
          "display-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
          "mono-timer": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
          "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
          "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
          "label-bold": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
          "body-base": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
